### PR TITLE
get category working

### PR DESCRIPTION
**Pull request by Leandro-Larrea**

### CODE REVIEW

**Comment by MatiasSoto21** [comment]
nice bro u very good

**Comment by MalenaLuana** [comment]
veery gud

**Review by MatiasSoto21 — APPROVED** [review]
boa manito

**Review by MalenaLuana — APPROVED** [review]

**Comment by Leandro-Larrea** [comment]
tenkiu

**Comment by Leandro-Larrea** [comment]
obrigado

**Review by MinNadia — APPROVED** [review]
okis

**Pull request merged**
